spring.application.name=FlightScanner

# Amadeus API Configuration
amadeus.client-id=${AMADEUS_CLIENT_ID:your-api-key}
amadeus.client-secret=${AMADEUS_CLIENT_SECRET:your-api-secret}
amadeus.environment=${AMADEUS_ENV:test}
